### ISSUE TITLE
have error while running this code

### ISSUE THREAD

**Issue by DasoTD** [pankazdebnath/Mail_Extractor#1]
= RESTART: C:/Users/KING DAVID/AppData/Local/Programs/Python/Python37/run.py =
Traceback (most recent call last):
  File "C:\Users\KING DAVID\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\KING DAVID\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\KING DAVID\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KING DAVID\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\KING DAVID\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by DasoTD** [comment]
sorted
